"""FastAPI-Mergen: principal-preserving transactional eventing."""

from fastapi_mergen._version import __version__
from fastapi_mergen.api import (
    AuthorizationMode,
    EffectContext,
    Event,
    Mergen,
    MergenUnitOfWork,
    Principal,
    RetryPolicy,
)
from fastapi_mergen.errors import (
    AuthenticationRequired,
    AuthorizationDenied,
    AuthorizationExpired,
    CommandConflict,
    CommandInProgress,
    DedupeConflict,
    LeaseLost,
    MergenConfigurationError,
    MergenError,
    MilestoneNotImplementedError,
    OptimisticConflict,
    OptionalDependencyError,
    PermanentDeliveryError,
    RetryableDeliveryError,
    SchemaRevisionMismatch,
)

__all__ = [
    "AuthenticationRequired",
    "AuthorizationDenied",
    "AuthorizationExpired",
    "AuthorizationMode",
    "CommandConflict",
    "CommandInProgress",
    "DedupeConflict",
    "EffectContext",
    "Event",
    "LeaseLost",
    "Mergen",
    "MergenConfigurationError",
    "MergenError",
    "MergenUnitOfWork",
    "MilestoneNotImplementedError",
    "OptimisticConflict",
    "OptionalDependencyError",
    "PermanentDeliveryError",
    "Principal",
    "RetryPolicy",
    "RetryableDeliveryError",
    "SchemaRevisionMismatch",
    "__version__",
]
