"""FastAPI Effects: principal-preserving transactional eventing."""

from fastapi_effects._version import __version__
from fastapi_effects.api import (
    AuthorizationMode,
    EffectContext,
    Event,
    FastAPIEffects,
    FastAPIEffectsUnitOfWork,
    Principal,
    RetryPolicy,
)
from fastapi_effects.errors import (
    AuthenticationRequired,
    AuthorizationDenied,
    AuthorizationExpired,
    CommandConflict,
    CommandInProgress,
    DedupeConflict,
    FastAPIEffectsConfigurationError,
    FastAPIEffectsError,
    LeaseLost,
    MilestoneNotImplementedError,
    OptimisticConflict,
    OptionalDependencyError,
    PermanentDeliveryError,
    RetryableDeliveryError,
    SchemaRevisionMismatch,
)

__all__ = [
    "AuthenticationRequired",
    "AuthorizationDenied",
    "AuthorizationExpired",
    "AuthorizationMode",
    "CommandConflict",
    "CommandInProgress",
    "DedupeConflict",
    "EffectContext",
    "Event",
    "FastAPIEffects",
    "FastAPIEffectsConfigurationError",
    "FastAPIEffectsError",
    "FastAPIEffectsUnitOfWork",
    "LeaseLost",
    "MilestoneNotImplementedError",
    "OptimisticConflict",
    "OptionalDependencyError",
    "PermanentDeliveryError",
    "Principal",
    "RetryPolicy",
    "RetryableDeliveryError",
    "SchemaRevisionMismatch",
    "__version__",
]
